/**
 * This file was automatically generated by generate-entity-index.js file
 * You can disable the automatic generation by removing the prepare section of the workspace.json file under api section
 */

// root.entity.ts
export * from "./lib/root.entity"

// todo.entity.ts
export * from "./lib/todo.entity"
