name: Delete review app

on:
  pull_request:
    types: [closed, locked]

jobs:
  delete-review-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup CI
        uses: ./.github/action-setup-ci
        with:
          github_token: ${{ github.token }}
          nx_cloud_token: ${{ secrets.NX_CLOUD_TOKEN }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Delete review app resources
        run: node node_modules/zx/zx.mjs ./.github/workflows/delete-digitalocean-review-app-resources.mjs
        env:
          PR_NUMBER: ${{ github.event.number }}
          REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
